


CREATE TABLE UNIDADES
(
COD_UNIDADE			INT IDENTITY NOT NULL,
NOME_UNIDADE		varchar(20) null,

CONSTRAINT COD_UNIDADE PRIMARY KEY(COD_UNIDADE)
);
Insert UNIDADES values ('PEÇAS')
Insert UNIDADES values ('METROS')
Insert UNIDADES values ('QUILOGRAMAS')
Insert UNIDADES values ('DÚZIAS')
Insert UNIDADES values ('PACOTE')
Insert UNIDADES values ('CAIXA')
SELECT*FROM UNIDADES;

CREATE TABLE CATEGORIAS
(
COD_CATEGORIA		INT IDENTITY NOT NULL,
NOME_CATEGORIA		varchar(20) null,

CONSTRAINT COD_CATEGORIA PRIMARY KEY(COD_CATEGORIA)
);
Insert CATEGORIAS values ('MOUSE')
Insert CATEGORIAS values ('PEN-DRIVE')
Insert CATEGORIAS values ('MONITOR DE VIDEO')
Insert CATEGORIAS values ('TECLADO')
Insert CATEGORIAS values ('CPU')
Insert CATEGORIAS values ('CABO DE REDE')

SELECT*FROM CATEGORIAS;

CREATE TABLE PRODUTOS
(
COD_PRODUTO			INT IDENTITY NOT NULL,
NOME_PRODUTO		VARCHAR(20) NOT NULL,
COD_UNIDADE			INT, --FK TABELA UNIDADE
COD_CATEGORIA		INT, --FK TABELA CATEGORIA
QUANT_ESTOQUE		NUMERIC(10) NOT NULL,
QUANT_MINIMA		NUMERIC(10) NOT NULL,
PRECO_CUSTO			NUMERIC(10,1) NOT NULL,
PRECO_VENDA			NUMERIC(10,2) NOT NULL,
CARACT_TECNICAS		VARCHAR(8000),

CONSTRAINT COD_PRODUTO PRIMARY KEY(COD_PRODUTO),
CONSTRAINT COD_UNIDADE_CHAVE_ESTRANGEIRA FOREIGN KEY(COD_UNIDADE)
REFERENCES UNIDADES(COD_UNIDADE),
CONSTRAINT COD_CATEGORIA_CHAVE_ESTRANGEIRA FOREIGN KEY(COD_CATEGORIA)
REFERENCES CATEGORIAS(COD_CATEGORIA)
);
DROP TABLE PRODUTOS
INSERT INTO PRODUTOS
(NOME_PRODUTO,COD_UNIDADE,COD_CATEGORIA, QUANT_ESTOQUE, QUANT_MINIMA, PRECO_CUSTO, PRECO_VENDA)
VALUES
('CANETA AZUL',1,1,150,40,0.5,0.75),
('CANETA VERDE',1,1,50,40,0.5,0.75),
('CANETA VERMELHA',1,1,80,35,0.5,0.75),
('LÁPIS',1,1,400,80,0.5,0.8),
('RÉGUA',1,1,40,10,1,1.5);

SELECT*FROM PRODUTOS;